// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBYSV5PXRche844mW68lHoXpoDVcP1If8',
    appId: '1:370840649730:web:d769b80818de3577e4671b',
    messagingSenderId: '370840649730',
    projectId: 'petra-coach-app',
    authDomain: 'petra-coach-app.firebaseapp.com',
    storageBucket: 'petra-coach-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_c46EyhbIdFTUwinJPzWNptKTmuutIk',
    appId: '1:370840649730:android:97d3bcfb9875e481e4671b',
    messagingSenderId: '370840649730',
    projectId: 'petra-coach-app',
    storageBucket: 'petra-coach-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6xerkuWlMYUj7DMHpqHRQp-WN2k7mai0',
    appId: '1:370840649730:ios:5f9a7d27782e02b0e4671b',
    messagingSenderId: '370840649730',
    projectId: 'petra-coach-app',
    storageBucket: 'petra-coach-app.firebasestorage.app',
    iosBundleId: 'com.petrasports.petraCoachApp',
  );
}
